/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 beats.gltf
Author: lazercar (https://sketchfab.com/lazercar)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/beats-studio-3-heaphones-80a807c2db784f48b93a9cccbb0df879
Title: Beats Studio 3 Heaphones
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Beats(props) {
  const { nodes, materials } = useGLTF('/beats.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 4, 0.2, 0]} scale={3}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.chrome_logo} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ear_cup} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.plastic} />
      </group>
    </group>
  )
}

useGLTF.preload('/beats.gltf')
