/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 vr.gltf
Author: Eternal Realm (https://sketchfab.com/EternalRealm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/htc-vive-4cee0970fe60444ead77d41fbb052a33
Title: HTC Vive
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Vr(props) {
  const { nodes, materials } = useGLTF('/vr.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.7}>
        <group position={[-3.93, -3.86, -2.42]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.base} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.black} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.dots} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.lens} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.logo} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.noise} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.screen} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.strap} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vr.gltf')
