/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 xbox.gltf
Author: arkanaulia (https://sketchfab.com/arkanaulia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/playstation-ps-5-xbox-x-one-fusion-controller-2c9b9882f4ca439e89e68cabbf49c767
Title: PlayStation PS 5 XBOX X ONE Fusion Controller
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Xbox(props) {
  const { nodes, materials } = useGLTF('/xbox.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group position={[0.2, 0.18, 0.32]} rotation={[0, 0, Math.PI / 2]} scale={0.95}>
          <group position={[2.99, 0.01, -5.45]} scale={[1, 1.04, 1]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Material} position={[-1.35, 0.04, -3.39]} rotation={[Math.PI, 0.95, Math.PI / 2]} scale={0.16} />
          </group>
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} position={[2.99, 0.01, -5.45]} scale={[1, 1.04, 1]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.008']} position={[-0.98, 4.6, -7.09]} scale={[1, 1.04, 1]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.008']} position={[-0.98, -4.6, -7.09]} scale={[1, 1.04, 1]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[2.99, 0.01, -5.45]} scale={[1, 1.04, 1]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.003']} position={[2.99, 0.01, -5.45]} scale={[1, 1.04, 1]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.004']} position={[2.99, 0.01, -5.45]} scale={[1, 1.04, 1]} />
        </group>
        <mesh geometry={nodes.Object_22.geometry} material={materials['phongE46SG.001']} position={[0.2, 0.2, 0.2]} rotation={[-2.19, 0, 0]} scale={0} />
      </group>
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.002']} position={[0.17, -0.2, 0.2]} rotation={[0.59, 1.47, -1.24]} scale={0.07} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.002']} position={[0.24, -0.2, 0.2]} rotation={[2.88, 1.45, 2.78]} scale={0.07} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.002']} position={[0.2, -0.25, 0.22]} rotation={[2.16, 1.56, -3.05]} scale={0.08} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.002']} position={[0.2, -0.25, 0.22]} rotation={[2.16, 1.56, -3.05]} scale={0.08} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.002']} position={[0.18, -0.24, 0.24]} rotation={[2.24, 1.46, -2.89]} scale={0.07} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.002']} position={[0.18, -0.24, 0.24]} rotation={[2.24, 1.46, -2.89]} scale={0.07} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.002']} position={[0.18, -0.24, 0.24]} rotation={[2.24, 1.46, -2.89]} scale={0.07} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.002']} position={[0.18, -0.24, 0.24]} rotation={[2.24, 1.46, -2.89]} scale={0.07} />
    </group>
  )
}

useGLTF.preload('/xbox.gltf')
